import { makeNode, makeLink, expose, evaluate } from './core.js';

export const L = (en, ca, es) => ({ en, ca, es });
const g = () => ({ nodes: [makeNode('input', 'GroupInput', 40, 180), makeNode('output', 'GroupOutput', 1320, 180)], links: [], exposed: [] });
const add = (graph, id, type, x, y, params) => { graph.nodes.push(makeNode(id, type, x, y, params)); return id; };
const link = (graph, from, out, to, input) => { graph.links.push(makeLink(from, out, to, input)); };
const plain = () => { const a = g(); link(a, 'input', 'Geometry', 'output', 'Geometry'); return a; };
const moved = () => { const a = g(); add(a, 'move', 'TransformGeometry', 490, 170, { Translation: [0, 0, 1] }); link(a, 'input', 'Geometry', 'move', 'Geometry'); link(a, 'move', 'Geometry', 'output', 'Geometry'); return a; };
function table(withInterface = false) {
  const a = g(); add(a, 'join', 'JoinGeometry', 1010, 160);
  const pieces = [
    { id: 'top', size: [3.4, 1.8, .22], position: [0, 0, 1.15] },
    ...[[-1.48, -.68], [1.48, -.68], [-1.48, .68], [1.48, .68]].map((p, i) => ({ id: `leg${i + 1}`, size: [.22, .22, 2.2], position: [p[0], p[1], 0] })),
  ];
  pieces.forEach((part, i) => { const x = 300 + (i % 2) * 275, y = 60 + Math.floor(i / 2) * 285; add(a, part.id, 'Cube', x, y, { Size: part.size }); add(a, `${part.id}Move`, 'TransformGeometry', x + 100, y + 145, { Translation: part.position }); link(a, part.id, 'Mesh', `${part.id}Move`, 'Geometry'); link(a, `${part.id}Move`, 'Geometry', 'join', 'Geometry'); });
  link(a, 'join', 'Geometry', 'output', 'Geometry');
  if (withInterface) expose(a, 'top', 'Size', 'Tabletop size');
  return a;
}
const grid = () => { const a = g(); add(a, 'grid', 'Grid', 340, 150); link(a, 'grid', 'Mesh', 'output', 'Geometry'); return a; };
function indexWave() {
  const a = grid(); add(a, 'set', 'SetPosition', 1000, 130); add(a, 'index', 'Index', 285, 530); add(a, 'sine', 'Math', 515, 500, { mode: 'Sine' }); add(a, 'amplitude', 'Math', 735, 500, { mode: 'Multiply', Value_001: .6 }); add(a, 'xyz', 'CombineXYZ', 980, 520);
  a.links = []; link(a, 'grid', 'Mesh', 'set', 'Geometry'); link(a, 'index', 'Index', 'sine', 'Value'); link(a, 'sine', 'Value', 'amplitude', 'Value'); link(a, 'amplitude', 'Value', 'xyz', 'Z'); link(a, 'xyz', 'Vector', 'set', 'Offset'); link(a, 'set', 'Geometry', 'output', 'Geometry'); return a;
}
function terrain(withInterface = false) {
  const a = grid(); a.nodes.find(n => n.id === 'grid').params['Vertices X'] = 18; a.nodes.find(n => n.id === 'grid').params['Vertices Y'] = 18;
  add(a, 'set', 'SetPosition', 1120, 130); add(a, 'position', 'Position', 265, 520); add(a, 'split', 'SeparateXYZ', 480, 505); add(a, 'sine', 'Math', 700, 505, { mode: 'Sine' }); add(a, 'amplitude', 'Math', 900, 505, { mode: 'Multiply', Value_001: .85 }); add(a, 'normal', 'Normal', 480, 815); add(a, 'vector', 'VectorMath', 1100, 540, { mode: 'Multiply' });
  a.links = []; link(a, 'grid', 'Mesh', 'set', 'Geometry'); link(a, 'position', 'Position', 'split', 'Vector'); link(a, 'split', 'X', 'sine', 'Value'); link(a, 'sine', 'Value', 'amplitude', 'Value'); link(a, 'normal', 'Normal', 'vector', 'Vector'); link(a, 'amplitude', 'Value', 'vector', 'Vector_001'); link(a, 'vector', 'Vector', 'set', 'Offset'); link(a, 'set', 'Geometry', 'output', 'Geometry');
  if (withInterface) expose(a, 'amplitude', 'Value_001', 'Terrain height');
  return a;
}
function distributed() { const a = g(); add(a, 'scatter', 'DistributePoints', 490, 170); link(a, 'input', 'Geometry', 'scatter', 'Mesh'); link(a, 'scatter', 'Points', 'output', 'Geometry'); return a; }
function instanced(random = false, selected = false) {
  const a = distributed(); add(a, 'collection', 'CollectionInfo', 510, 610); add(a, 'instances', 'InstanceOnPoints', 1010, 170);
  a.links = a.links.filter(l => l.to !== 'output'); link(a, 'scatter', 'Points', 'instances', 'Points'); link(a, 'collection', 'Instances', 'instances', 'Instance'); link(a, 'instances', 'Instances', 'output', 'Geometry');
  if (random) {
    add(a, 'random', 'RandomValue', 745, 650);
    add(a, 'turn', 'RandomValue', 745, 920, { Min: 0, Max: 6.28, Seed: 7 });
    add(a, 'rotationVector', 'CombineXYZ', 1010, 900);
    add(a, 'rotation', 'EulerToRotation', 1250, 900);
    link(a, 'random', 'Value', 'instances', 'Scale');
    link(a, 'turn', 'Value', 'rotationVector', 'Z');
    link(a, 'rotationVector', 'Vector', 'rotation', 'Euler');
    link(a, 'rotation', 'Rotation', 'instances', 'Rotation');
  }
  if (selected) {
    add(a, 'position', 'Position', 260, 830); add(a, 'split', 'SeparateXYZ', 470, 830); add(a, 'greater', 'Math', 690, 850, { mode: 'Greater Than', Value_001: 0 });
    link(a, 'position', 'Position', 'split', 'Vector'); link(a, 'split', 'Z', 'greater', 'Value'); link(a, 'greater', 'Value', 'scatter', 'Selection'); expose(a, 'scatter', 'Density', 'Rock density');
  }
  return a;
}
function rail() { const a = g(); add(a, 'line', 'CurveLine', 290, 160); add(a, 'profile', 'CurveCircle', 290, 560); add(a, 'mesh', 'CurveToMesh', 760, 160); link(a, 'line', 'Curve', 'mesh', 'Curve'); link(a, 'profile', 'Curve', 'mesh', 'Profile Curve'); link(a, 'mesh', 'Mesh', 'output', 'Geometry'); return a; }
function railPoints() { const a = g(); add(a, 'line', 'CurveLine', 280, 170); add(a, 'resample', 'ResampleCurve', 560, 170); add(a, 'points', 'CurveToPoints', 840, 170); link(a, 'line', 'Curve', 'resample', 'Curve'); link(a, 'resample', 'Curve', 'points', 'Curve'); link(a, 'points', 'Points', 'output', 'Geometry'); return a; }
function fence(withInterface = false) {
  const a = rail(); add(a, 'resample', 'ResampleCurve', 510, 700); add(a, 'points', 'CurveToPoints', 780, 700); add(a, 'post', 'Cube', 780, 990, { Size: [.14, .14, 2] }); add(a, 'instances', 'InstanceOnPoints', 1060, 700); add(a, 'join', 'JoinGeometry', 1210, 190);
  a.links = a.links.filter(l => l.to !== 'output'); link(a, 'line', 'Curve', 'resample', 'Curve'); link(a, 'resample', 'Curve', 'points', 'Curve'); link(a, 'points', 'Points', 'instances', 'Points'); link(a, 'post', 'Mesh', 'instances', 'Instance'); link(a, 'mesh', 'Mesh', 'join', 'Geometry'); link(a, 'instances', 'Instances', 'join', 'Geometry'); link(a, 'join', 'Geometry', 'output', 'Geometry');
  if (withInterface) { expose(a, 'line', 'End', 'Fence end'); expose(a, 'resample', 'Count', 'Number of posts'); expose(a, 'profile', 'Radius', 'Rail radius'); }
  return a;
}
const count = (graph, type) => graph.nodes.filter(n => n.type === type).length;
const wired = (graph, type, input) => graph.links.some(l => graph.nodes.find(n => n.id === l.to)?.type === type && l.input === input);
const output = graph => graph.links.some(l => l.to === 'output' && l.input === 'Geometry');
const step = (title, aim, how, why, starter, solution, check) => ({ title, aim, how, why, starter, solution, check });

export const LABS = {
  1: {
    title: L('GN 01 · Geometry flow', 'GN 01 · El flux de la geometria', 'GN 01 · El flujo de la geometría'),
    lead: L('A node tree fills the Geometry Nodes modifier. Start with a wire, then build a table from primitives.', 'Un arbre de nodes omple el modificador Geometry Nodes. Comença amb una connexió i acaba construint una taula amb primitives.', 'Un árbol de nodos llena el modificador Geometry Nodes. Empieza con una conexión y termina construyendo una mesa con primitivas.'),
    challenge: L('A table made entirely from primitives', 'Una taula feta només amb primitives', 'Una mesa hecha solo con primitivas'),
    steps: [
      step(L('Geometry enters and leaves', 'La geometria entra i surt', 'La geometría entra y sale'), L('Connect Group Input to Group Output.', 'Connecta Group Input amb Group Output.', 'Conecta Group Input con Group Output.'), [L('Drag from the Geometry output to the Geometry input.', 'Arrossega Geometry de la sortida a l’entrada.', 'Arrastra Geometry desde la salida a la entrada.'), L('The modifier is the box; the tree decides its contents.', 'El modificador és la caixa; l’arbre en decideix el contingut.', 'El modificador es la caja; el árbol decide su contenido.')], L('Without a route to Group Output, nothing is visible.', 'Sense una ruta fins a Group Output no es veu res.', 'Sin una ruta hasta Group Output no se ve nada.'), g, plain, (a, r) => output(a) && r.stats.meshes === 1),
      step(L('Move the incoming geometry', 'Mou la geometria que entra', 'Mueve la geometría que entra'), L('Insert Transform Geometry and lift the cube.', 'Insereix Transform Geometry i aixeca el cub.', 'Inserta Transform Geometry y eleva el cubo.'), [L('Add Transform Geometry between the group nodes.', 'Afegeix Transform Geometry entre els nodes del grup.', 'Añade Transform Geometry entre los nodos del grupo.'), L('Set Translation Z to at least 0.5 m.', 'Posa Translation Z com a mínim a 0,5 m.', 'Pon Translation Z como mínimo en 0,5 m.')], L('The geometry socket carries the whole object; Translation is one vector value.', 'El socket Geometry transporta tot l’objecte; Translation és un únic vector.', 'El socket Geometry transporta todo el objeto; Translation es un único vector.'), plain, moved, (a, r) => wired(a, 'TransformGeometry', 'Geometry') && r.geometry.meshes.some(m => m.position[2] >= .5)),
      step(L('Build the table', 'Construeix la taula', 'Construye la mesa'), L('Join a tabletop and four legs made with Cube and Transform Geometry.', 'Uneix un tauler i quatre potes fets amb Cube i Transform Geometry.', 'Une un tablero y cuatro patas hechos con Cube y Transform Geometry.'), [L('Give each cube its own size and location.', 'Dona una mida i una posició a cada cub.', 'Da un tamaño y una posición a cada cubo.'), L('Send the five pieces into Join Geometry, then Group Output.', 'Envia les cinc peces a Join Geometry i després a Group Output.', 'Envía las cinco piezas a Join Geometry y después a Group Output.')], L('Join Geometry can accept several geometry wires in the same socket.', 'Join Geometry accepta diverses connexions de geometria al mateix socket.', 'Join Geometry acepta varias conexiones de geometría en el mismo socket.'), moved, () => table(), (a, r) => count(a, 'Cube') >= 5 && count(a, 'TransformGeometry') >= 5 && count(a, 'JoinGeometry') >= 1 && r.stats.meshes >= 5),
      step(L('Expose a modifier control', 'Exposa un control al modificador', 'Expón un control en el modificador'), L('Expose the tabletop size so it can be changed from the modifier.', 'Exposa la mida del tauler per poder-la canviar des del modificador.', 'Expón el tamaño del tablero para poder cambiarlo desde el modificador.'), [L('Use the Expose button beside the Size input.', 'Fes servir Exposa al costat de l’entrada Size.', 'Usa Exponer al lado de la entrada Size.'), L('Change the value in the modifier panel and watch the table.', 'Canvia el valor al panell del modificador i observa la taula.', 'Cambia el valor en el panel del modificador y observa la mesa.')], L('An exposed value becomes a Group Input socket; the modifier supplies its value.', 'Un valor exposat esdevé un socket de Group Input; el modificador en proporciona el valor.', 'Un valor expuesto pasa a ser un socket de Group Input; el modificador proporciona su valor.'), () => table(), () => table(true), (a, r) => r.stats.meshes >= 5 && a.exposed?.some(e => e.targetSocket === 'Size')),
    ],
  },
  2: {
    title: L('GN 02 · Fields and attributes', 'GN 02 · Camps i atributs', 'GN 02 · Campos y atributos'),
    lead: L('A field is an instruction evaluated at every point. Shape a grid and read its values in the spreadsheet.', 'Un camp és una instrucció que s’avalua a cada punt. Deforma un Grid i llegeix-ne els valors al full de dades.', 'Un campo es una instrucción evaluada en cada punto. Deforma un Grid y lee sus valores en la hoja de datos.'),
    challenge: L('A procedural terrain from a grid', 'Un terreny procedural a partir d’un Grid', 'Un terreno procedural a partir de un Grid'),
    steps: [
      step(L('Inspect the grid', 'Inspecciona el Grid', 'Inspecciona el Grid'), L('Output a Grid and open the Spreadsheet.', 'Envia un Grid a la sortida i obre el Spreadsheet.', 'Envía un Grid a la salida y abre el Spreadsheet.'), [L('Connect Grid › Mesh to Group Output › Geometry.', 'Connecta Grid › Mesh amb Group Output › Geometry.', 'Conecta Grid › Mesh con Group Output › Geometry.'), L('In the Spreadsheet, compare Index and Position for neighbouring vertices.', 'Al Spreadsheet, compara Index i Position en vèrtexs veïns.', 'En Spreadsheet, compara Index y Position en vértices vecinos.')], L('One filled socket is a single value; a diamond field can differ at each vertex.', 'Un socket ple és un valor únic; un camp en rombe pot variar a cada vèrtex.', 'Un socket redondo es un valor único; un campo en rombo puede variar en cada vértice.'), g, grid, (a, r, f) => r.stats.vertices >= 64 && f.spreadsheet),
      step(L('Index makes a wave', 'Index crea una onada', 'Index crea una onda'), L('Use Index → Math Sine → Combine XYZ → Set Position.', 'Fes servir Index → Math Sine → Combine XYZ → Set Position.', 'Usa Index → Math Sine → Combine XYZ → Set Position.'), [L('Connect the field to Offset Z through Combine XYZ.', 'Connecta el camp a Offset Z mitjançant Combine XYZ.', 'Conecta el campo a Offset Z mediante Combine XYZ.'), L('Change the Math multiplier and compare the vertex heights.', 'Canvia el multiplicador de Math i compara les altures.', 'Cambia el multiplicador de Math y compara las alturas.')], L('Index is evaluated once for every point; Sine turns it into a repeating height.', 'Index s’avalua a cada punt; Sine el converteix en una altura repetitiva.', 'Index se evalúa en cada punto; Sine lo convierte en una altura repetida.'), grid, indexWave, (a, r) => count(a, 'Index') && count(a, 'SetPosition') && r.stats.maxZ - r.stats.minZ > .3),
      step(L('Position and Normal', 'Position i Normal', 'Position y Normal'), L('Use Position X to make a broad wave and Normal to choose its direction.', 'Fes servir Position X per fer una onada ampla i Normal per orientar-la.', 'Usa Position X para crear una onda amplia y Normal para orientarla.'), [L('Separate X from Position and send it through Sine.', 'Separa X de Position i passa’l per Sine.', 'Separa X de Position y pásalo por Sine.'), L('Multiply Normal by that height with Vector Math.', 'Multiplica Normal per aquesta altura amb Vector Math.', 'Multiplica Normal por esa altura con Vector Math.')], L('The same field graph is evaluated using a different position at every vertex.', 'El mateix graf de camps es calcula amb una posició diferent a cada vèrtex.', 'El mismo grafo de campos se calcula con otra posición en cada vértice.'), indexWave, () => terrain(), (a, r) => count(a, 'Position') && count(a, 'Normal') && count(a, 'VectorMath') && r.stats.maxZ - r.stats.minZ > .4),
      step(L('Terrain with a height control', 'Terreny amb control d’altura', 'Terreno con control de altura'), L('Expose the wave amplitude and finish a reusable terrain.', 'Exposa l’amplitud de l’onada i acaba un terreny reutilitzable.', 'Expón la amplitud de la onda y termina un terreno reutilizable.'), [L('Expose the second Value of the Multiply node.', 'Exposa el segon Value del node Multiply.', 'Expón el segundo Value del nodo Multiply.'), L('Use the modifier value to tune the relief.', 'Ajusta el relleu amb el valor del modificador.', 'Ajusta el relieve con el valor del modificador.')], L('GN 03 will use this terrain as its input geometry in the same browser.', 'GN 03 farà servir aquest terreny com a geometria d’entrada al mateix navegador.', 'GN 03 usará este terreno como geometría de entrada en el mismo navegador.'), () => terrain(), () => terrain(true), (a, r) => a.exposed?.some(e => e.targetSocket === 'Value_001') && r.stats.maxZ - r.stats.minZ > .4),
    ],
  },
  3: {
    title: L('GN 03 · Instances and scatter', 'GN 03 · Instàncies i scatter', 'GN 03 · Instancias y scatter'),
    lead: L('Scatter rocks over the terrain from GN 02. Control where they appear, vary their size, and keep them as efficient instances.', 'Escampa pedres sobre el terreny del GN 02. Controla on apareixen, varia’n la mida i mantén-les com a instàncies eficients.', 'Esparce rocas por el terreno de GN 02. Controla dónde aparecen, varía su tamaño y mantenlas como instancias eficientes.'),
    challenge: L('Rocks on the terrain, controlled by a field', 'Pedres sobre el terreny, controlades per un camp', 'Rocas sobre el terreno, controladas por un campo'),
    steps: [
      step(L('Distribute the points', 'Distribueix els punts', 'Distribuye los puntos'), L('Use Distribute Points on Faces with Density and Seed.', 'Fes servir Distribute Points on Faces amb Density i Seed.', 'Usa Distribute Points on Faces con Density y Seed.'), [L('Connect the incoming terrain to Mesh.', 'Connecta el terreny d’entrada a Mesh.', 'Conecta el terreno de entrada a Mesh.'), L('Change Seed: the count may stay similar, but positions change.', 'Canvia Seed: la quantitat pot ser semblant, però les posicions canvien.', 'Cambia Seed: la cantidad puede ser similar, pero las posiciones cambian.')], L('Density controls how many points are proposed per surface area.', 'Density regula quants punts es proposen per superfície.', 'Density regula cuántos puntos se proponen por superficie.'), plain, distributed, (a, r) => count(a, 'DistributePoints') && r.stats.points >= 8),
      step(L('Put rocks on points', 'Posa pedres als punts', 'Pon rocas en los puntos'), L('Feed Collection Info into Instance on Points.', 'Connecta Collection Info a Instance on Points.', 'Conecta Collection Info a Instance on Points.'), [L('Points carry positions; Instance supplies the rock geometry.', 'Points transporta posicions; Instance aporta la geometria de la pedra.', 'Points transporta posiciones; Instance aporta la geometría de la roca.'), L('Use the Rocks collection, then inspect the instance count.', 'Fes servir la col·lecció Rocks i mira la quantitat d’instàncies.', 'Usa la colección Rocks y mira la cantidad de instancias.')], L('An instance refers to source geometry instead of making a full new mesh each time.', 'Una instància fa referència a la geometria original sense duplicar tota la malla.', 'Una instancia hace referencia a la geometría original sin duplicar toda la malla.'), distributed, () => instanced(), (a, r) => count(a, 'CollectionInfo') && count(a, 'InstanceOnPoints') && r.stats.instances >= 8),
      step(L('Vary every rock', 'Varia cada pedra', 'Varía cada roca'), L('Use Random Value for both Scale and Rotation.', 'Fes servir Random Value per a Scale i Rotation.', 'Usa Random Value para Scale y Rotation.'), [L('Connect one Random Value (0.55–1.25) to Scale.', 'Connecta un Random Value (0,55–1,25) a Scale.', 'Conecta un Random Value (0,55–1,25) a Scale.'), L('Connect another (0–6.28) through Combine XYZ and Euler to Rotation; change a Seed.', 'Connecta’n un altre (0–6,28) a Combine XYZ (Z) i Euler to Rotation; canvia un Seed.', 'Conecta otro (0–6,28) a Combine XYZ (Z) y Euler to Rotation; cambia un Seed.')], L('The same Seed and point index always give the same value.', 'El mateix Seed i índex de punt sempre donen el mateix valor.', 'El mismo Seed e índice de punto siempre dan el mismo valor.'), () => instanced(), () => instanced(true), (a, r) => wired(a, 'InstanceOnPoints', 'Scale') && wired(a, 'InstanceOnPoints', 'Rotation') && count(a, 'EulerToRotation') && count(a, 'RandomValue') >= 2 && new Set(r.geometry.meshes.map(m => m.size[0].toFixed(2))).size >= 3 && new Set(r.geometry.meshes.map(m => m.rotationZ?.toFixed(2))).size >= 3),
      step(L('Mask the scatter', 'Emmascara l’scatter', 'Enmascara el scatter'), L('Use a Position field for Selection and expose Density.', 'Fes servir un camp de Position per a Selection i exposa Density.', 'Usa un campo de Position para Selection y expón Density.'), [L('Compare points above and below Z = 0 with Greater Than.', 'Compara els punts per sobre i per sota de Z = 0 amb Greater Than.', 'Compara los puntos por encima y por debajo de Z = 0 con Greater Than.'), L('Try Realize Instances, then remove it: scattering usually stays more efficient without it.', 'Prova Realize Instances i després treu-lo: normalment l’scatter és més eficient sense aquest node.', 'Prueba Realize Instances y luego quítalo: normalmente el scatter es más eficiente sin ese nodo.')], L('Realize is useful only when a later operation needs real, individually editable geometry.', 'Realize convé quan una operació posterior necessita geometria real i editable individualment.', 'Realize conviene cuando una operación posterior necesita geometría real y editable por separado.'), () => instanced(true), () => instanced(true, true), (a, r, f) => wired(a, 'DistributePoints', 'Selection') && a.exposed?.some(e => e.targetSocket === 'Density') && r.stats.instances >= 3 && f.realizeCompared),
    ],
  },
  4: {
    title: L('GN 04 · Curves and final project', 'GN 04 · Corbes i projecte final', 'GN 04 · Curvas y proyecto final'),
    lead: L('Turn a curve into rails, sample it into points, and place repeated posts. Finish with modifier controls for a procedural fence.', 'Converteix una corba en passamans, mostra’n punts i col·loca-hi pals repetits. Acaba amb controls al modificador per a una tanca procedural.', 'Convierte una curva en barandales, muéstrala en puntos y coloca postes repetidos. Termina con controles en el modificador para una valla procedural.'),
    challenge: L('A procedural fence with adjustable length, posts and rail', 'Una tanca procedural de llargada, pals i passamà ajustables', 'Una valla procedural con longitud, postes y barandal ajustables'),
    steps: [
      step(L('Give a curve a profile', 'Dona un perfil a una corba', 'Da un perfil a una curva'), L('Curve Line + Curve Circle → Curve to Mesh.', 'Curve Line + Curve Circle → Curve to Mesh.', 'Curve Line + Curve Circle → Curve to Mesh.'), [L('Connect Line to Curve and Circle to Profile Curve.', 'Connecta Line a Curve i Circle a Profile Curve.', 'Conecta Line a Curve y Circle a Profile Curve.'), L('The profile radius controls the thickness of the rail.', 'El radi del perfil regula el gruix del passamà.', 'El radio del perfil regula el grosor del barandal.')], L('Curve to Mesh sweeps the profile along the whole path.', 'Curve to Mesh escombra el perfil al llarg de tot el traçat.', 'Curve to Mesh barre el perfil a lo largo de todo el trazado.'), g, rail, (a, r) => count(a, 'CurveLine') && count(a, 'CurveCircle') && r.stats.tubes >= 1),
      step(L('Sample the curve', 'Mostreja la corba', 'Muestrea la curva'), L('Use Resample Curve and Curve to Points to choose post positions.', 'Fes servir Resample Curve i Curve to Points per triar les posicions dels pals.', 'Usa Resample Curve y Curve to Points para elegir las posiciones de los postes.'), [L('Change Count and watch the spacing in the preview and spreadsheet.', 'Canvia Count i observa la separació a la vista i al Spreadsheet.', 'Cambia Count y observa la separación en la vista y en Spreadsheet.')], L('Resample Curve makes an even set of control points along the line.', 'Resample Curve crea punts repartits regularment al llarg de la línia.', 'Resample Curve crea puntos repartidos regularmente a lo largo de la línea.'), rail, railPoints, (a, r, f) => count(a, 'ResampleCurve') && count(a, 'CurveToPoints') && r.stats.points >= 5 && f.spreadsheet),
      step(L('Join rails and posts', 'Uneix passamà i pals', 'Une barandal y postes'), L('Instance a Cube on each point, then Join Geometry with the rail.', 'Instancia un Cube a cada punt i uneix-los amb el passamà a Join Geometry.', 'Instancia un Cube en cada punto y únelos con el barandal en Join Geometry.'), [L('One branch makes the rail; another makes the post instances.', 'Una branca fa el passamà; l’altra fa les instàncies dels pals.', 'Una rama hace el barandal; la otra crea las instancias de postes.'), L('Join both branches before Group Output.', 'Uneix les dues branques abans de Group Output.', 'Une las dos ramas antes de Group Output.')], L('This combines geometry flow, sampled points and instances in one tree.', 'Això combina flux de geometria, punts mostrejats i instàncies en un sol arbre.', 'Esto combina flujo de geometría, puntos muestreados e instancias en un árbol.'), railPoints, () => fence(), (a, r) => count(a, 'JoinGeometry') && r.stats.tubes >= 1 && r.stats.instances >= 5),
      step(L('Make the fence reusable', 'Fes la tanca reutilitzable', 'Haz la valla reutilizable'), L('Expose length, post count and rail radius in the modifier.', 'Exposa llargada, nombre de pals i radi del passamà al modificador.', 'Expón longitud, número de postes y radio del barandal en el modificador.'), [L('Expose Curve Line › End, Resample Curve › Count and Curve Circle › Radius.', 'Exposa Curve Line › End, Resample Curve › Count i Curve Circle › Radius.', 'Expón Curve Line › End, Resample Curve › Count y Curve Circle › Radius.'), L('Change the modifier values and check that the whole fence responds.', 'Canvia els valors del modificador i comprova que tota la tanca respon.', 'Cambia los valores del modificador y comprueba que toda la valla responde.')], L('The final group can be reused for more than one fence length.', 'El grup final es pot reutilitzar per a tanques de llargades diferents.', 'El grupo final puede reutilizarse para vallas de longitudes distintas.'), () => fence(), () => fence(true), (a, r) => a.exposed?.length >= 3 && r.stats.tubes >= 1 && r.stats.instances >= 5),
    ],
  },
};

export const local = (text, lang = 'ca') => typeof text === 'string' ? text : (text?.[lang] || text?.en || '');
export function solutionPasses() {
  return Object.entries(LABS).map(([id, lab]) => lab.steps.map((s, i) => {
    const graph = s.solution(), result = evaluate(graph, { lab: Number(id) });
    return { lab: Number(id), step: i + 1, ok: !!s.check(graph, result, { spreadsheet: true, realizeCompared: true }), errors: result.errors };
  })).flat();
}
