// Material Lab: what every parameter does. Shown as an extended Blender-style tooltip when the pointer
// rests on a field (or the field gets keyboard focus). Texts are in English; i18n.js translates them.
// at: where the card attaches — 'field:key' (a value field), 'socket:key' (a socket row), 'id:key' (an element
// by id, its row), 'panel:key' (a Principled panel header), 'setting:key' (a Properties control) or a CSS selector.
export const PARAMS = {
 // ─── Principled BSDF · main inputs ──────────────────────────────────────────
 base: { at: 'field:base', name: 'Base Color',
  what: 'The colour of the surface: the diffuse colour of a non-metal, or the colour of the reflection of a metal. Keep light and shadow out of it: a Base Color texture should look flat, like the object under a cloudy sky.',
  range: 'Real surfaces go from about 30 (charcoal) to about 240 (fresh snow) in sRGB. Never pure black or pure white.',
  examples: [['Charcoal', '#333333'], ['Concrete', '#8a8a86'], ['White paint', '#e6e6e6'], ['Gold (metal)', '#ffe29b'], ['Copper (metal)', '#fad0c0'], ['Iron (metal)', '#c4c7c7']],
  mistake: 'Pure white (255) or baked-in shadows: the material reflects more light than anything real and stops matching the lights.' },
 metallic: { at: 'field:metallic', name: 'Metallic',
  what: 'Says whether the surface is a metal. A metal has no diffuse colour: all its colour goes into the reflection. A non-metal (plastic, wood, stone, skin, paint) has a coloured diffuse and a weak white reflection.',
  range: '0 or 1. Values in between only for the edge between two materials, and they come from a mask texture.',
  examples: [['Plastic, wood, paint', '0'], ['Steel, gold, chrome', '1'], ['Rust on iron', 'mask 0/1'], ['Painted metal, scratched', 'mask']],
  mistake: 'Metallic 0.5 on a whole object: it looks like dirty plastic. And painted metal is not metal: the paint is on top.' },
 roughness: { at: 'field:roughness', name: 'Roughness',
  what: 'How rough the surface is at a microscopic scale. At 0 the reflection is a perfect mirror; the higher it gets, the more the reflection spreads and blurs, until it becomes a soft sheen. It is the most important value after Base Color.',
  range: '0 to 1. Almost nothing is 0 or 1. Most real materials are between 0.3 and 0.8.',
  examples: [['Mirror, chrome', '0.02'], ['Polished metal', '0.15'], ['Glossy plastic', '0.3'], ['Satin paint', '0.5'], ['Wood, skin', '0.6'], ['Concrete, chalk', '0.9']],
  mistake: 'Using one flat value. Real surfaces vary: fingerprints, wear and dust belong in a Roughness texture (Non-Color).' },
 ior: { at: 'field:ior', name: 'IOR',
  what: 'Index of refraction. For glass and water it says how much the light bends when it goes through. For every non-metal it also sets how strong the reflection is facing the camera (the Fresnel effect): 1.5 gives about 4%.',
  range: '1 (air, no reflection) to about 2.5. Metals ignore it.',
  examples: [['Water', '1.33'], ['Skin, ice', '1.4'], ['Plastic, glass', '1.5'], ['Crystal', '1.6'], ['Diamond', '2.42']],
  mistake: 'Changing IOR to make something shinier. For shine use Roughness; IOR is a physical property of the material.' },
 alpha: { at: 'field:alpha', name: 'Alpha',
  what: 'How much of the surface exists. At 0 the surface is not there at all, at 1 it is solid. It is for cut-outs: leaves, hair cards, fences, decals, with a black and white mask.',
  range: '0 to 1. Usually a mask texture (Non-Color): white = there, black = cut out.',
  examples: [['Leaf card', 'mask'], ['Chain-link fence', 'mask'], ['Fading hologram', '0.3']],
  mistake: 'Using Alpha for glass. Alpha removes the surface (no reflection, no refraction); glass is Transmission.',
  engine: 'EEVEE: works with the default Render Method (Dithered); Blended is for soft semi-transparent surfaces and sorts badly.' },
 normal: { at: 'socket:bsdf:normal', name: 'Normal',
  what: 'The direction the surface faces in every point, used for the lighting. Connect a Normal Map node (from a normal map image) or a Bump node (from a height map) to add detail without geometry.',
  range: 'A vector socket: it takes the output of Normal Map or Bump, never an image directly.',
  examples: [['Brick joints', 'Normal Map'], ['Scratches, pores', 'Bump'], ['Baked high poly', 'Normal Map']],
  mistake: 'Connecting the normal map image straight into Normal, or leaving it as sRGB: the light bends the wrong way.' },

 // ─── Panels ────────────────────────────────────────────────────────────────
 p_subsurface: { at: 'panel:subsurface', name: 'Subsurface',
  what: 'Light that goes into the surface, scatters inside and comes out somewhere else. Shadows become soft and coloured and thin parts glow against the light.',
  range: 'For skin, wax, marble, jade, milk, fruit, leaves. Weight 0 turns it off.',
  examples: [['Skin', 'Weight 1'], ['Candle wax', 'Weight 1'], ['Plastic toy', '0']],
  mistake: 'Leaving it on for hard materials: stone walls or wood then look like soap.' },
 p_specular: { at: 'panel:specular', name: 'Specular',
  what: 'Fine control of the reflection: its strength and colour for non-metals, and anisotropy (stretched highlights) for brushed surfaces.',
  range: 'The defaults are physically correct. Change them only with a reason.',
  examples: [['Brushed steel', 'Anisotropic 0.8'], ['Pearl, car flakes', 'Tint']],
  mistake: 'Using IOR Level as a shininess slider. Shininess is Roughness.' },
 p_transmission: { at: 'panel:transmission', name: 'Transmission',
  what: 'Light that goes through the surface and bends: glass, water, gems, clear plastic. The Base Color tints the light that passes, Roughness frosts it and IOR bends it.',
  range: 'Weight 0 (opaque) or 1 (transparent).',
  examples: [['Window glass', '1'], ['Frosted glass', '1, Roughness 0.3'], ['Wine', '1, dark red Base Color']],
  mistake: 'Transmission with Metallic 1: metals are never transparent, the metal wins.' },
 p_coat: { at: 'panel:coat', name: 'Coat',
  what: 'A thin clear layer on top of everything: varnish, lacquer, the clear coat of a car. It adds a second, sharper reflection over the base.',
  range: 'Weight 0 or 1; Roughness low (0 to 0.1) for polished coats.',
  examples: [['Car paint', '1'], ['Varnished wood', '1'], ['Wet surface', '0.6']],
  mistake: 'Coat Roughness as high as the base: the two reflections merge and the layer is lost.' },
 p_sheen: { at: 'panel:sheen', name: 'Sheen',
  what: 'A soft glow at grazing angles made by tiny fibres: velvet, cloth, dust, peach skin.',
  range: 'Weight 0 to 1; Roughness about 0.5.',
  examples: [['Velvet', '1'], ['Cotton', '0.4'], ['Dusty object', '0.3']],
  mistake: 'Expecting it facing the camera: sheen lives at the silhouette.' },
 p_emission: { at: 'panel:emission', name: 'Emission',
  what: 'Light made by the surface itself: screens, LEDs, lava, neon. It is added on top of the shading and does not depend on the lights.',
  range: 'Strength 0 turns it off.',
  examples: [['Phone screen', '1–3'], ['Neon sign', '5–20'], ['Lava', '5–10']],
  mistake: 'Expecting a halo: glow is the Glare node in the Compositor, not the material.' },
 p_thinfilm: { at: 'panel:thinfilm', name: 'Thin Film',
  what: 'A very thin transparent film on the surface that makes rainbow colours by interference: soap bubbles, oil stains, heat-tinted metal.',
  range: 'Thickness 0 turns it off.',
  examples: [['Soap bubble', '300–600 nm'], ['Oil on water', '300–500 nm'], ['Titanium, burnt pipe', '200–400 nm']],
  mistake: 'Very thick films (thousands of nm): the colours mix back into white.' },

 // ─── Panels · values ───────────────────────────────────────────────────────
 subsurface: { at: 'field:subsurface', name: 'Subsurface › Weight',
  what: 'How much of the diffuse light scatters under the surface instead of bouncing right at it.',
  range: '0 (off) to 1. Skin and wax use 1; the Radius and the Scale decide the look.',
  examples: [['Skin', '1'], ['Marble', '1'], ['Painted wall', '0']],
  mistake: 'Using Weight to make it subtle: keep Weight at 1 and make the Scale smaller.' },
 subRadius: { at: 'css:[data-panel="subsurface"] .vec3', name: 'Subsurface › Radius',
  what: 'How far red, green and blue travel inside, relative to each other. The biggest value is the colour that bleeds most.',
  range: 'Three values. In skin red goes furthest, so the shadow edge turns red.',
  examples: [['Skin (default)', '1, 0.2, 0.1'], ['Jade', '0.4, 1, 0.5'], ['Milk', '1, 1, 1']],
  mistake: 'Radius as the colour of the material: the colour is still the Base Color.' },
 subScale: { at: 'field:subScale', name: 'Subsurface › Scale',
  what: 'Multiplies the Radius: the real distance light travels, in scene units (metres).',
  range: 'Depends on the size of the object: small for a real-size head, bigger for big wax objects.',
  examples: [['Human skin, real size', '0.01–0.05'], ['Candle', '0.05–0.1'], ['Big marble statue', '0.1–0.3']],
  mistake: 'A Scale too big for the object: it looks like jelly. Check the scale of the object is applied.' },
 specLevel: { at: 'field:specLevel', name: 'Specular › IOR Level',
  what: 'Scales the reflection of non-metals given by the IOR. 0.5 means "exactly what the IOR says".',
  range: '0 = no reflection, 0.5 = physical, 1 = double.',
  examples: [['Everything real', '0.5'], ['Rubber (softer)', '0.3–0.4'], ['Stylised, no reflection', '0']],
  mistake: 'Raising it to make something look wet or shiny: lower Roughness instead.' },
 specTint: { at: 'id:specTint', name: 'Specular › Tint',
  what: 'Colours the reflection. For non-metals it tints the reflection facing the camera; for metals it tints the edges (grazing angles).',
  range: 'White for almost everything.',
  examples: [['Most materials', 'white'], ['Gold edge warmth', 'light yellow'], ['Car paint flakes', 'subtle colour']],
  mistake: 'Colouring plastic reflections: real plastic reflects white.' },
 aniso: { at: 'field:aniso', name: 'Specular › Anisotropic',
  what: 'Stretches the highlight in one direction, like the grooves of brushed metal. It needs some Roughness: a mirror has nothing to stretch.',
  range: '0 (round highlight) to 1 (very stretched).',
  examples: [['Brushed aluminium', '0.7'], ['Pan bottom', '0.8'], ['Hair (simple)', '0.9']],
  mistake: 'Bad UVs: the direction follows the Tangent (the UVs by default), so twisted UVs twist the highlight.' },
 anisoRot: { at: 'field:anisoRot', name: 'Specular › Anisotropic Rotation',
  what: 'Turns the direction of the stretch around the normal.',
  range: '0 to 1 is a full turn: 0.25 = 90°.',
  examples: [['Along U', '0'], ['Along V', '0.25']],
  mistake: 'Rotating it instead of fixing the UVs of the brushed parts.' },
 transmission: { at: 'field:transmission', name: 'Transmission › Weight',
  what: 'How much light goes through the surface instead of being scattered by it.',
  range: '0 or 1. Metallic must be 0. The object must be closed and have thickness.',
  examples: [['Glass', '1'], ['Water', '1, IOR 1.33'], ['Wood', '0']],
  mistake: 'Glass as a single plane: it cannot bend light like a solid. Model the thickness (or use Solidify).',
  engine: 'EEVEE refracts the objects behind only with Raytracing (Render) and Raytraced Transmission (Material Settings); Cycles always does.' },
 coat: { at: 'field:coat', name: 'Coat › Weight',
  what: 'How much of the clear layer covers the base.',
  range: '0 or 1 for a coat that is there or not; in between for wet or partly varnished surfaces.',
  examples: [['Car paint', '1'], ['Wet pavement', '0.5–0.8'], ['Matte wood', '0']],
  mistake: 'Adding a coat to metals by default: polished metal is already a sharp reflection.' },
 coatRough: { at: 'field:coatRough', name: 'Coat › Roughness',
  what: 'How rough the clear layer is. It is independent from the Roughness of the base.',
  range: '0 to 0.1 for polished coats; higher for satin varnish.',
  examples: [['New car', '0.02'], ['Satin varnish', '0.25']],
  mistake: 'Making it rougher than the base: the coat then blurs everything under it.' },
 coatIor: { at: 'field:coatIor', name: 'Coat › IOR',
  what: 'The IOR of the coat: how strong its reflection is facing the camera.',
  range: 'About 1.5 for varnish and lacquer.',
  examples: [['Lacquer, varnish', '1.5'], ['Water film', '1.33']],
  mistake: 'Raising it to make the coat stronger: use Weight.' },
 coatTint: { at: 'id:coatTint', name: 'Coat › Tint',
  what: 'The colour of the coat itself: light that goes through it to the base and back gets tinted.',
  range: 'White for clear coats; a light colour for tinted varnish.',
  examples: [['Clear coat', 'white'], ['Amber varnish', 'light orange'], ['Candy paint', 'saturated colour']],
  mistake: 'Dark tints: the whole object goes dark because the light passes through the coat twice.' },
 sheen: { at: 'field:sheen', name: 'Sheen › Weight',
  what: 'How strong the fibre layer is.',
  range: '0 to 1.',
  examples: [['Velvet', '1'], ['Cotton, wool', '0.3–0.6'], ['Leather', '0']],
  mistake: 'A bright sheen on a bright base: it only shows well on darker cloth.' },
 sheenRough: { at: 'field:sheenRough', name: 'Sheen › Roughness',
  what: 'How wide the sheen is: low values give a thin rim at the silhouette, high values a broad soft glow.',
  range: '0 to 1, default 0.5.',
  examples: [['Velvet', '0.3–0.5'], ['Felt', '0.8']],
  mistake: 'Confusing it with the Roughness of the base, which is separate.' },
 sheenTint: { at: 'id:sheenTint', name: 'Sheen › Tint',
  what: 'The colour of the fibres in the light.',
  range: 'White or a light version of the cloth colour.',
  examples: [['Velvet', 'white or light pink'], ['Silk-like', 'light tint of the base']],
  mistake: 'Saturated tints: sheen is light scattered by fibres, close to white.' },
 emission: { at: 'field:emission', name: 'Emission › Color',
  what: 'The colour of the light the surface gives off. Usually an image for screens and signs.',
  range: 'Any colour; black turns it off like Strength 0.',
  examples: [['Screen', 'image texture'], ['Warm bulb', 'light orange']],
  mistake: 'Putting the colour only in Base Color: without Emission it does not glow in the dark.' },
 emissionStrength: { at: 'field:emissionStrength', name: 'Emission › Strength',
  what: 'How bright the emitted light is. At 1 the colour appears at its own value; above 1 it is brighter than white and the Glare node can catch it.',
  range: '0 (off) upwards. It is relative to the exposure of the scene.',
  examples: [['Dim display', '0.5–1'], ['Neon', '5–20'], ['Light panel', '10+']],
  mistake: 'Using emission instead of lamps in EEVEE: it will not light the scene unless Raytracing (or baked probes) catch it.',
  engine: 'Cycles lights the scene with it; EEVEE only on screen with Raytracing.' },
 tfThick: { at: 'field:tfThick', name: 'Thin Film › Thickness',
  what: 'The thickness of the film in nanometres. Each thickness reinforces other wavelengths, so it sets which colours appear.',
  range: '0 (off). Colourful between about 100 and 1000 nm.',
  examples: [['Soap bubble', '300–600'], ['Oil film', '300–500'], ['Heat-tinted steel', '100–300']],
  mistake: 'A single thickness everywhere looks flat: real bubbles vary; a noise texture on Thickness helps.' },
 tfIor: { at: 'field:tfIor', name: 'Thin Film › IOR',
  what: 'The index of refraction of the film material. It changes the colours and how strong they are.',
  range: 'About 1.3 to 2.5.',
  examples: [['Soapy water', '1.33'], ['Oil', '1.47'], ['Titanium oxide', '2–2.5']],
  mistake: 'Leaving the main IOR at 1.5 for a bubble: a bubble is a thin skin of water with air inside, so the main IOR is 1.0.' },

 // ─── Other nodes ───────────────────────────────────────────────────────────
 strength: { at: 'field:strength', name: 'Normal Map › Strength',
  what: 'How strongly the normal map bends the lighting.',
  range: '1 = as the map was made. 0 to 2 is the usual range.',
  examples: [['Baked map', '1'], ['Subtle wall detail', '0.5'], ['Stylised, strong', '1.5']],
  mistake: 'Pushing it to 3 or more to fix a weak map: the shading breaks at the edges. The map should be right from the start.' },
 bumpStrength: { at: 'field:bumpStrength', name: 'Bump › Strength',
  what: 'How much the height map bends the normals.',
  range: '0 to 1. Small values are usually enough.',
  examples: [['Pores, scratches', '0.1–0.3'], ['Tile joints', '0.5–1']],
  mistake: 'Big bumps: they look fake at grazing angles because the silhouette stays flat. Use displacement for big shapes.' },
 dispMid: { at: 'field:dispMid', name: 'Displacement › Midlevel',
  what: 'The value of the height map that means "do not move". Brighter pixels go out, darker go in.',
  range: '0.5 for maps made around mid-grey; 0 when black means the surface itself.',
  examples: [['Sculpt bake (grey)', '0.5'], ['Tiles, black joints = base', '0']],
  mistake: 'A wrong Midlevel moves the whole surface out or in, as if the object had grown.' },
 dispScale: { at: 'field:dispScale', name: 'Displacement › Scale',
  what: 'How far white moves the surface, in scene units (metres) along the normal.',
  range: 'Blender starts at 1 m, which is far too much for most maps: real relief is centimetres.',
  examples: [['Tiles', '0.01–0.03'], ['Stone wall', '0.05'], ['Terrain', 'metres']],
  mistake: 'Forgetting it is in metres: a 0.1 m scale on a 20 cm object destroys it.' },
 colorSpace: { at: 'css:.color-space', name: 'Image Texture › Color Space',
  what: 'How the numbers of the image are read. sRGB decodes the screen curve for colour images; Non-Color reads the numbers as they are, for data.',
  range: 'sRGB: Base Color, Emission images. Non-Color: Roughness, Metallic, Normal, Height, masks.',
  examples: [['Base Color', 'sRGB'], ['Roughness', 'Non-Color'], ['Normal map', 'Non-Color']],
  mistake: 'A normal map or roughness in sRGB: the values bend and the material looks wrong without an obvious reason.' },
 mappingType: { at: 'css:.mapping-type', name: 'Mapping › Type',
  what: 'How the transform is applied. Point moves the coordinates; Texture moves the texture (the opposite direction); Vector and Normal are for directions.',
  range: 'Point is the usual one for Image Textures.',
  examples: [['Tiling a texture', 'Point'], ['Moving a decal like an object', 'Texture']],
  mistake: 'Expecting Scale 2 to make the texture bigger in Point: it repeats it twice, so the pattern gets smaller.' },
 location: { at: 'css:[data-vector-field="location"]', name: 'Mapping › Location',
  what: 'Shifts the coordinates: slides the texture over the surface.',
  range: 'In UV units: 1 = the whole image.',
  examples: [['Offset half a tile', '0.5'], ['Hide a seam', 'small offsets']],
  mistake: 'Moving only one map: Base Color, Roughness and Normal must share the same Mapping.' },
 rotation: { at: 'css:[data-vector-field="rotation"]', name: 'Mapping › Rotation',
  what: 'Turns the coordinates. For UV textures, rotate around Z.',
  range: 'Degrees.',
  examples: [['Wood grain across', 'Z 90°']],
  mistake: 'Rotating around X or Y on a flat UV map: the image squashes instead of turning.' },
 scale: { at: 'css:[data-vector-field="scale"]', name: 'Mapping › Scale',
  what: 'Multiplies the coordinates: bigger values repeat the texture more times, so each tile is smaller.',
  range: 'Same X and Y to keep the proportions.',
  examples: [['Brick wall 4× tiles', '4, 4, 1'], ['Stretch fix', 'different X and Y']],
  mistake: 'Different X and Y by accident: squashed bricks. Z does nothing on flat UV images.' },
 texcoord: { at: 'css:#node-coordinates .node-body', name: 'Texture Coordinate',
  what: 'Where the coordinates come from. UV uses the unwrap; Generated and Object use the position on the mesh; Normal, Camera, Window and Reflection are directions or screen positions.',
  range: 'UV for textures painted or made for the model; Object or Generated for procedural textures.',
  examples: [['Image textures', 'UV'], ['Procedural noise', 'Object'], ['Fake chrome', 'Reflection']],
  mistake: 'Object coordinates on a moving deformed character: the texture swims. Use UV.' },
 invert: { at: 'css:#node-invert .static-bar', name: 'Invert Color',
  what: 'Turns every value upside down: 1 − value. Black becomes white.',
  range: 'Fac 1 inverts fully.',
  examples: [['Gloss → Roughness', 'Fac 1'], ['Smoothness (Unity) → Roughness', 'Fac 1']],
  mistake: 'Inverting a normal map with it: normal maps need their green channel flipped, not all channels.' },
 output: { at: 'socket:output:displacement', name: 'Material Output › Displacement',
  what: 'Where height goes to move the surface. What it does depends on Material Properties › Settings › Displacement.',
  range: 'Bump Only (default): shading only. Displacement Only or Displacement and Bump: the mesh moves, if it has enough vertices.',
  examples: [['Close-up terrain', 'Displacement and Bump'], ['Game asset', 'Bump Only + normal map']],
  mistake: 'Connecting it and expecting the mesh to move with the default setting.' },

 // ─── Properties editor ─────────────────────────────────────────────────────
 engine: { at: 'setting:engine', name: 'Render Engine',
  what: 'EEVEE is real-time: fast, approximate, some effects need extra settings. Cycles traces light paths: slower, physically based, with real refraction, caustics and emission lighting.',
  range: 'EEVEE for look development, games-like previews, motion graphics; Cycles for final realistic renders.',
  examples: [['Glass and water', 'Cycles'], ['Stylised animation', 'EEVEE']],
  mistake: 'Judging a glass or an emissive material only in EEVEE without its settings.' },
 raytracing: { at: 'setting:raytracing', name: 'Raytracing (EEVEE)',
  what: 'Lets EEVEE trace reflections, refraction and indirect light on screen. Without it, EEVEE uses light probes and the world.',
  range: 'On for glass, glossy floors and emissive lights; off for speed.',
  examples: [['Glass refraction', 'on'], ['Emission lighting the room', 'on']],
  mistake: 'Expecting it to see objects off screen: it only traces what the camera sees.' },
 glare: { at: 'setting:glare', name: 'Glare node · Bloom',
  what: 'A Compositor node that spreads the brightest pixels into a halo, like a camera lens. It works for EEVEE and Cycles.',
  range: 'Between Render Layers and Composite, type Bloom.',
  examples: [['Neon signs', 'Bloom'], ['Sun on metal', 'Streaks or Bloom']],
  mistake: 'Looking for a Bloom checkbox in EEVEE: it is a Compositor node now.' },
 glareThreshold: { at: 'setting:glareThreshold', name: 'Glare › Threshold',
  what: 'Only pixels brighter than this value glow. 1 means brighter than white.',
  range: '1 is a good start; lower values make more things glow.',
  examples: [['Only emitters', '1–2'], ['Dreamy look', '0.5']],
  mistake: 'Threshold 0: the whole image glows and loses contrast.' },
 glareStrength: { at: 'setting:glareStrength', name: 'Glare › Strength',
  what: 'How much of the halo is added to the image.',
  range: '0 to about 1 for realistic lenses.',
  examples: [['Subtle', '0.3'], ['Stylised', '1']],
  mistake: 'Hiding a weak emission with a strong glare: raise Emission Strength instead.' },
 glareSize: { at: 'setting:glareSize', name: 'Glare › Size',
  what: 'How wide the halo spreads.',
  range: 'Small for tight glows, large for haze.',
  examples: [['LED', 'small'], ['Foggy night', 'large']],
  mistake: 'A huge size on small lights: the halo looks like fog.' },
 vpCompositor: { at: 'setting:vpCompositor', name: 'Viewport Shading › Compositor',
  what: 'Runs the Compositor nodes in the viewport too, so you see Glare and colour work while you model.',
  range: 'Disabled, Camera (only in camera view) or Always.',
  examples: [['Working on glow', 'Always'], ['Modelling', 'Disabled']],
  mistake: 'Thinking the Glare node does not work because the viewport does not show it.' },
 subdiv: { at: 'id:subdiv', name: 'Subdivision Surface › Levels Viewport',
  what: 'Splits every face into four, level after level. Simple keeps the shape; Catmull-Clark also smooths it.',
  range: 'Each level multiplies the faces by 4: level 7 turns one face into 16 384.',
  examples: [['Displacement close-up', '6–8'], ['Smooth low poly', '1–2']],
  mistake: 'Very high levels in the viewport: everything slows down. Use a lower viewport level and a higher render level.' },
 adaptive: { at: 'setting:adaptive', name: 'Adaptive Subdivision (Cycles)',
  what: 'Cycles subdivides at render time: more near the camera, less far away, so displacement gets dense geometry only where it is seen.',
  range: 'Cycles only. Set on the Subdivision Surface modifier.',
  examples: [['Terrain', 'on'], ['EEVEE scene', 'no effect']],
  mistake: 'Turning it on in EEVEE and wondering why nothing changes.' },
 dispMod: { at: 'setting:dispMod', name: 'Displace modifier',
  what: 'Moves the vertices with a texture as a modifier: real geometry, visible in every engine and mode, and it can be applied.',
  range: 'Needs enough vertices (a Subdivision Surface above it in the stack).',
  examples: [['Game asset', 'modifier, then apply'], ['Animated waves', 'modifier with a moving texture']],
  mistake: 'Putting it above the Subdivision Surface: it only moves the few original vertices.' },
 modStrength: { at: 'setting:modStrength', name: 'Displace › Strength',
  what: 'How far white moves the vertices, in scene units.',
  range: 'Centimetres for surface relief.',
  examples: [['Tiles', '0.02'], ['Rocky ground', '0.2']],
  mistake: 'Negative values push the relief inwards: sometimes that is what you want (engraved text).' },
 modMid: { at: 'setting:modMid', name: 'Displace › Midlevel',
  what: 'The texture value that does not move the vertices.',
  range: '0.5 for mid-grey maps, 0 when black is the base surface.',
  examples: [['Height bake', '0.5'], ['Black background mask', '0']],
  mistake: 'A wrong Midlevel lifts the whole surface.' },
 dispMethod: { at: 'setting:dispMethod', name: 'Settings › Displacement',
  what: 'What the Material Output › Displacement socket does. Bump Only: shading only (default). Displacement Only: the mesh moves. Displacement and Bump: the mesh moves and small detail stays as bump.',
  range: 'Displacement and Bump is the usual choice for true displacement.',
  examples: [['Games, fast renders', 'Bump Only'], ['Close-up stone wall', 'Displacement and Bump']],
  mistake: 'Leaving Bump Only and blaming the node tree.',
  engine: 'EEVEE displaces too, and treats Displacement Only as Displacement and Bump.' },
 rtTransmission: { at: 'setting:rtTransmission', name: 'Settings › Raytraced Transmission',
  what: 'EEVEE material setting: refract what is on screen with Raytracing instead of only the light probes.',
  range: 'On for glass and water that must show the objects behind them. Needs Raytracing in the render settings.',
  examples: [['Glass of water on a table', 'on'], ['Frosted window, far', 'off']],
  mistake: 'Turning it on without Raytracing: nothing changes.' },
};
